package com.jiaul.websocket_chatapp_server.enums;

public enum AuthEnum {
    USERNAME_ALREADY_TAKEN,
    REGISTRATION_SUCCESS,
    REGISTRATION_FAILED,
    INTERNAL_SERVER_ERROR,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT_SUCCESS,
    WEB_SOCKET_CONNECTED,
    WEB_SOCKET_IS_NOT_CONNECTED,
    WEB_SOCKET_TOKEN_UPDATED,
}
